// =============================================================================
// DATA — loaded from JSON files generated by scripts/extract_data.py
// =============================================================================
let DATA = { act1: null, act2: null, act3: null, act4: null };
let act4Chart = null;

async function loadAllData() {
  try {
    const [a1, a2, a3, a4] = await Promise.all([
      fetch('../js/act1_revolution.json').then(r => r.json()),
      fetch('../js/act2_bubbles.json').then(r => r.json()),
      fetch('../js/act3_players.json').then(r => r.json()),
      fetch('../js/act4_dynasties.json').then(r => r.json()),
    ]);
    DATA.act1 = a1;
    DATA.act2 = a2;
    DATA.act3 = a3;
    DATA.act4 = a4;
    console.log('✓ All data loaded');
    initAct3Defaults();
    buildDynastyLegend();
  } catch(e) {
    console.warn('Could not load JSON files. Run scripts/extract_data.py first.', e);
  }
}

// =============================================================================
// SECTION SWITCHER
// =============================================================================
const sections = ['hero','act1','act2','act3','act4'];

function showSection(id) {
  sections.forEach(s => {
    const el = document.getElementById(s);
    el.style.display = 'none';
    el.classList.remove('visible');
  });
  const target = document.getElementById(id);
  target.style.display = 'flex';
  target.classList.add('visible');
  document.querySelectorAll('.nav-act').forEach(el => {
    el.classList.toggle('active', el.textContent.toLowerCase().includes(id === 'hero' ? 'home' : id));
  });
  window.scrollTo(0, 0);
  if (id === 'act1' && DATA.act1) drawAct1(act1Step);
  if (id === 'act2' && DATA.act2) drawAct2();
  if (id === 'act3' && DATA.act3) drawRadar();
  if (id === 'act4' && DATA.act4) drawAct4();
}

// =============================================================================
// SVG HELPER + TOOLTIP
// =============================================================================
function mkSvg(tag, attrs) {
  const el = document.createElementNS('http://www.w3.org/2000/svg', tag);
  Object.entries(attrs).forEach(([k, v]) => el.setAttribute(k, v));
  return el;
}
function showTip(e, name, stat) {
  const t = document.getElementById('tooltip');
  document.getElementById('tt-name').textContent = name;
  document.getElementById('tt-stat').textContent = stat;
  t.style.display = 'block';
}
function hideTip() { document.getElementById('tooltip').style.display = 'none'; }
document.addEventListener('mousemove', e => {
  const t = document.getElementById('tooltip');
  if (t.style.display === 'block') { t.style.left = (e.clientX+12)+'px'; t.style.top = (e.clientY-10)+'px'; }
});

// =============================================================================
// ACT 1 — 3-Point Revolution
// =============================================================================
let act1Step = 0;
const act1StepSeasons = [1983, 1997, 2013, 2017, 2026];

function act1Go(step, el) {
  act1Step = step;
  document.querySelectorAll('.story-block').forEach(b => b.classList.remove('active'));
  el.classList.add('active');
  if (DATA.act1) drawAct1(step);
}

function drawAct1(step) {
  const d = DATA.act1;
  const svg = document.getElementById('act1-chart');
  svg.innerHTML = '';
  const W = 560, H = 280, pad = { l:45, r:20, t:20, b:35 };
  const iw = W-pad.l-pad.r, ih = H-pad.t-pad.b;
  const maxV = Math.max(...d.x3pa) * 1.05;
  const minS = d.seasons[0], maxS = d.seasons[d.seasons.length-1];
  const xS = s => pad.l + (s-minS)/(maxS-minS)*iw;
  const yS = v => pad.t + ih - v/maxV*ih;

  // Grid
  [0,5,10,15,20,25,30,35].forEach(v => {
    if (v > maxV) return;
    const y = yS(v);
    svg.appendChild(mkSvg('line',{x1:pad.l,x2:W-pad.r,y1:y,y2:y,stroke:'rgba(255,255,255,0.05)','stroke-width':'1'}));
    const t = mkSvg('text',{x:pad.l-6,y:y+4,fill:'#6a7592','font-size':'9','text-anchor':'end'});
    t.textContent = v; svg.appendChild(t);
  });
  [1980,1990,2000,2010,2020,2026].forEach(yr => {
    if (yr < minS || yr > maxS) return;
    const x = xS(yr);
    const t = mkSvg('text',{x,y:H-pad.b+14,fill:'#6a7592','font-size':'9','text-anchor':'middle'});
    t.textContent = yr; svg.appendChild(t);
  });

  // Shaded area
  const cutoff = act1StepSeasons[step];
  const vis = d.seasons.map((s,i)=>({s,v:d.x3pa[i]})).filter(p=>p.s<=cutoff);
  if (vis.length > 1) {
    const first = vis[0], last = vis[vis.length-1];
    svg.appendChild(mkSvg('polygon',{
      points:`${xS(first.s)},${yS(0)} ${vis.map(p=>`${xS(p.s)},${yS(p.v)}`).join(' ')} ${xS(last.s)},${yS(0)}`,
      fill:'rgba(232,98,26,0.08)',stroke:'none'
    }));
  }

  // Full line (faint)
  svg.appendChild(mkSvg('polyline',{points:d.seasons.map((s,i)=>`${xS(s)},${yS(d.x3pa[i])}`).join(' '),fill:'none',stroke:'rgba(232,98,26,0.2)','stroke-width':'1.5'}));

  // Highlighted portion
  const hlPts = d.seasons.map((s,i)=>({s,v:d.x3pa[i]})).filter(p=>p.s<=cutoff).map(p=>`${xS(p.s)},${yS(p.v)}`).join(' ');
  if (hlPts) svg.appendChild(mkSvg('polyline',{points:hlPts,fill:'none',stroke:'var(--accent)','stroke-width':'2.5','stroke-linecap':'round'}));

  // Annotations
  d.annotations.filter((_,i)=>i<=step).forEach(a => {
    const idx = d.seasons.indexOf(a.season);
    if (idx === -1) return;
    const cx = xS(a.season), cy = yS(d.x3pa[idx]);
    svg.appendChild(mkSvg('circle',{cx,cy,r:'5',fill:'var(--accent)',stroke:'var(--bg2)','stroke-width':'2'}));
    const words = a.label.split(' ');
    const mid = Math.ceil(words.length/2);
    [words.slice(0,mid).join(' '), words.slice(mid).join(' ')].filter(Boolean).forEach((ln,i) => {
      const t = mkSvg('text',{x:cx+8,y:cy-12+i*11,fill:'var(--text)','font-size':'9','font-weight':'600'});
      t.textContent = ln; svg.appendChild(t);
    });
  });
}

// =============================================================================
// ACT 2 — Era Explorer Bubble Chart
// =============================================================================
const posColors = {PG:'#4fc3f7',SG:'#e8621a',SF:'#66bb6a',PF:'#ab47bc',C:'#ef5350'};
let currentYear = 2015, highlightName = '', playing = false, playInterval = null;

function highlightPlayer(val) { highlightName = val.toLowerCase(); drawAct2(); }
function updateYear(val) {
  currentYear = parseInt(val);
  document.getElementById('year-display').textContent = currentYear;
  drawAct2();
}
function togglePlay() {
  playing = !playing;
  const icon = document.getElementById('play-icon');
  if (playing) {
    icon.innerHTML = '<rect x="3" y="2" width="3" height="10" fill="white"/><rect x="8" y="2" width="3" height="10" fill="white"/>';
    playInterval = setInterval(() => {
      currentYear = currentYear >= 2026 ? 1982 : currentYear + 1;
      document.getElementById('year-slider').value = currentYear;
      document.getElementById('year-display').textContent = currentYear;
      drawAct2();
    }, 180);
  } else {
    icon.innerHTML = '<polygon points="3,1 13,7 3,13"/>';
    clearInterval(playInterval);
  }
}

function drawAct2() {
  if (!DATA.act2) return;
  const players = DATA.act2[String(currentYear)];
  if (!players) return;
  const svg = document.getElementById('act2-chart');
  svg.innerHTML = '';
  const W=700,H=360,pad={l:50,r:20,t:20,b:40};
  const iw=W-pad.l-pad.r,ih=H-pad.t-pad.b;
  const xS = u => pad.l+(u-10)/(38-10)*iw;
  const yS = t => pad.t+ih-(t-44)/(72-44)*ih;

  for(let t=45;t<=70;t+=5){
    const y=yS(t);
    svg.appendChild(mkSvg('line',{x1:pad.l,x2:W-pad.r,y1:y,y2:y,stroke:'rgba(255,255,255,0.05)','stroke-width':'1'}));
    const tx=mkSvg('text',{x:pad.l-6,y:y+4,fill:'#6a7592','font-size':'9','text-anchor':'end'});
    tx.textContent=t+'%'; svg.appendChild(tx);
  }
  for(let u=10;u<=38;u+=5){
    const x=xS(u);
    svg.appendChild(mkSvg('line',{x1:x,x2:x,y1:pad.t,y2:H-pad.b,stroke:'rgba(255,255,255,0.05)','stroke-width':'1'}));
    const tx=mkSvg('text',{x,y:H-pad.b+14,fill:'#6a7592','font-size':'9','text-anchor':'middle'});
    tx.textContent=u+'%'; svg.appendChild(tx);
  }
  const xl=mkSvg('text',{x:W/2,y:H-2,fill:'#6a7592','font-size':'10','text-anchor':'middle'});
  xl.textContent='Usage Rate %'; svg.appendChild(xl);

  players.forEach(p => {
    const cx=xS(p.usg_percent), cy=yS(p.ts_percent), r=4+p.mp_per_game*0.16;
    const isHL = highlightName && p.player.toLowerCase().includes(highlightName);
    const c=mkSvg('circle',{cx,cy,r,fill:posColors[p.pos]||'#6a7592',opacity:isHL?'1':'0.65','stroke-width':isHL?'2':'0',stroke:'white'});
    c.style.cursor='pointer';
    c.addEventListener('mouseenter',e=>showTip(e,p.player,`${p.pos} · USG ${p.usg_percent}% · TS ${p.ts_percent}% · ${p.pts_per_game} PPG`));
    c.addEventListener('mouseleave',hideTip);
    svg.appendChild(c);
    if(isHL||p.mp_per_game>35){
      const t=mkSvg('text',{x:cx,y:cy-r-3,fill:'white','font-size':'9','text-anchor':'middle','font-weight':'600'});
      t.textContent=p.player.split(' ').slice(-1)[0]; svg.appendChild(t);
    }
  });
}

// =============================================================================
// ACT 3 — Player Comparison Radar
// =============================================================================
let playerA=null, playerB=null, radarMode='normalized';
const METRICS=['pts_per_game','trb_per_game','ast_per_game','ts_percent','ws_48','bpm','vorp','per'];
const STAT_LABELS=['Points / game','Rebounds / game','Assists / game','True Shooting %','Win Shares / 48','BPM','VORP','PER'];
const LABELS=['PTS','REB','AST','TS%','WS/48','BPM','VORP','PER'];

function initAct3Defaults() {
  if (!DATA.act3) return;
  const s = DATA.act3.search;
  const lb = s.find(p=>p.name==='LeBron James');
  const mj = s.find(p=>p.name==='Michael Jordan');
  if (lb) selectAct3Player('A', lb.id);
  if (mj) selectAct3Player('B', mj.id);
}

function searchPlayer(slot, query) {
  if (!DATA.act3) return;
  const list = document.getElementById('list'+slot);
  if (!query.trim()) { list.classList.remove('open'); return; }
  const results = DATA.act3.search.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())).slice(0,8);
  list.innerHTML = results.map(p=>`<div class="autocomplete-item" onclick="selectAct3Player('${slot}','${p.id}')"><span>${p.name}</span><span class="seasons">${p.seasons}</span></div>`).join('');
  list.classList.toggle('open', results.length>0);
}

function selectAct3Player(slot, pid) {
  if (!DATA.act3) return;
  const p = DATA.act3.players[pid];
  if (!p) return;
  if (slot==='A') { playerA={id:pid,...p}; document.getElementById('nameA').textContent=p.name; document.getElementById('legend-a').textContent='■ '+p.name.split(' ')[0]; document.getElementById('searchA').value=p.name; }
  else { playerB={id:pid,...p}; document.getElementById('nameB').textContent=p.name; document.getElementById('legend-b').textContent='■ '+p.name.split(' ')[0]; document.getElementById('searchB').value=p.name; }
  document.getElementById('list'+slot).classList.remove('open');
  renderStatTables(); drawRadar();
}

function renderStatTables() {
  ['A','B'].forEach(slot => {
    const player = slot==='A'?playerA:playerB;
    const other  = slot==='A'?playerB:playerA;
    const container = document.getElementById('stats'+slot);
    const cls = slot==='A'?'highlight-a':'highlight-b';
    if (!player||!container) return;
    container.innerHTML = METRICS.map((m,i)=>{
      const val = player.stats[m];
      const display = val!==undefined?(m==='ws_48'?val.toFixed(3):val.toFixed(1)):'—';
      const better = other && val > other.stats[m];
      return `<div class="stat-row"><span>${STAT_LABELS[i]}</span><span class="stat-val ${better?cls:''}">${display}</span></div>`;
    }).join('');
  });
}

function setMode(mode, btn) {
  radarMode = mode;
  document.querySelectorAll('.toggle-btn').forEach(b=>b.classList.remove('active'));
  btn.classList.add('active');
  drawRadar();
}

function drawRadar() {
  const svg = document.getElementById('radar-chart');
  svg.innerHTML = '';
  if (!playerA && !playerB) return;
  const cx=120,cy=120,R=88,n=LABELS.length;
  const angle = i => (i/n)*Math.PI*2-Math.PI/2;
  const pt = (i,r) => [cx+Math.cos(angle(i))*r, cy+Math.sin(angle(i))*r];

  [0.25,0.5,0.75,1].forEach(f=>{
    const pts=LABELS.map((_,i)=>pt(i,R*f).join(',')).join(' ');
    svg.appendChild(mkSvg('polygon',{points:pts,fill:'none',stroke:'rgba(255,255,255,0.07)','stroke-width':'1'}));
  });
  LABELS.forEach((label,i)=>{
    const [x,y]=pt(i,R);
    svg.appendChild(mkSvg('line',{x1:cx,y1:cy,x2:x,y2:y,stroke:'rgba(255,255,255,0.07)','stroke-width':'1'}));
    const [lx,ly]=pt(i,R+14);
    const t=mkSvg('text',{x:lx,y:ly+4,fill:'#6a7592','font-size':'8','text-anchor':'middle'});
    t.textContent=label; svg.appendChild(t);
  });

  function drawPoly(player, fill, stroke) {
    if (!player) return;
    const src = radarMode==='normalized'?player.normalized:player.stats;
    const rawScales={pts_per_game:40,trb_per_game:15,ast_per_game:12,ts_percent:70,ws_48:0.3,bpm:15,vorp:15,per:35};
    const vals=METRICS.map(m=>{
      let v=src[m]||0;
      if(radarMode==='raw') v=Math.min(100,Math.max(0,(v/rawScales[m])*100));
      return Math.min(100,Math.max(0,v));
    });
    const pts=vals.map((v,i)=>pt(i,R*v/100).join(',')).join(' ');
    svg.appendChild(mkSvg('polygon',{points:pts,fill,stroke,'stroke-width':'2'}));
    vals.forEach((v,i)=>{ const [x,y]=pt(i,R*v/100); svg.appendChild(mkSvg('circle',{cx:x,cy:y,r:'3',fill:stroke})); });
  }
  drawPoly(playerA,'rgba(29,111,232,0.2)','var(--accent2)');
  drawPoly(playerB,'rgba(232,98,26,0.2)','var(--accent)');
}

document.addEventListener('click', e => {
  if (!e.target.closest('.search-wrap')) document.querySelectorAll('.autocomplete-list').forEach(l=>l.classList.remove('open'));
});

// =============================================================================
// ACT 4 — Dynasties Line Chart (Chart.js)
// =============================================================================
let activeTeams = new Set(['Bulls','Lakers','Spurs','Heat','Warriors','Celtics']);

function buildDynastyLegend() {
  if (!DATA.act4) return;
  const legend = document.getElementById('dynasty-legend');
  Object.entries(DATA.act4).forEach(([name, d]) => {
    const item = document.createElement('div');
    item.className = 'dynasty-dot active';
    item.id = 'leg-' + name;
    item.innerHTML = `<span style="background:${d.color}"></span>${name}`;
    item.onclick = () => toggleDynasty(name);
    legend.appendChild(item);
  });
}

function toggleDynasty(name) {
  if (activeTeams.has(name)) {
    if (activeTeams.size === 1) return; // keep at least one
    activeTeams.delete(name);
    document.getElementById('leg-'+name).classList.remove('active');
  } else {
    activeTeams.add(name);
    document.getElementById('leg-'+name).classList.add('active');
  }
  drawAct4();
}

function drawAct4() {
  if (!DATA.act4) return;

  const datasets = Object.entries(DATA.act4)
    .filter(([name]) => activeTeams.has(name))
    .map(([name, d]) => ({
      label: name,
      data: d.seasons.map((s, i) => ({ x: s, y: d.wins[i] })),
      borderColor: d.color,
      backgroundColor: d.color + '18',
      borderWidth: 2.5,
      pointRadius: 3,
      pointHoverRadius: 6,
      pointBackgroundColor: d.color,
      tension: 0.3,
      fill: false,
    }));

  if (act4Chart) {
    act4Chart.data.datasets = datasets;
    act4Chart.update();
    return;
  }

  const gridColor = 'rgba(255,255,255,0.05)';
  const textColor = '#6a7592';

  act4Chart = new Chart(document.getElementById('act4-chart'), {
    type: 'line',
    data: { datasets },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      interaction: { mode: 'nearest', intersect: false, axis: 'x' },
      plugins: {
        legend: { display: false },
        tooltip: {
          backgroundColor: '#1a2235',
          borderColor: 'rgba(255,255,255,0.07)',
          borderWidth: 1,
          titleColor: '#e8e8f0',
          bodyColor: '#6a7592',
          callbacks: {
            title: () => '',
            label: ctx => ' Win%: ' + Math.round(ctx.raw.y * 100) + '%',
          }
        }
      },
      scales: {
        x: {
          type: 'linear', min: 1990, max: 2026,
          ticks: { color: textColor, stepSize: 5, callback: v => v },
          grid: { color: gridColor },
        },
        y: {
          min: 0.2, max: 1.0,
          ticks: { color: textColor, callback: v => Math.round(v*100)+'%' },
          grid: { color: gridColor },
        }
      }
    }
  });
}

// =============================================================================
// INIT
// =============================================================================
loadAllData().then(() => showSection('hero'));